### ISSUE TITLE
Contato

### ISSUE THREAD

**Issue by SamuelSSan28** [mateusap1/athena#3]
@mateusap1 não consegui achar nenhuma forma de conversar contigo pra entender mais do projeto e poder ajudar. Foi o jeito por aqui. Manda um email pra gente ir se falando, caso queira mais contribuidores pro projeto. 

Meu email: samuelssan28@gmail.com.

**Comment by mateusap1** [comment]
Desculpa por não ter feito contato, eu to meio ocupado nesses dias, mas já vou te mandar um e-mail explicando o projeto.

**Comment by SamuelSSan28** [comment]
De boa, só reabri pra ter certeza que você veria. Fiquei na dúvida kkkkkk, e como achei bem interessante a ideia não podia perder a oportunidade.
